#!/usr/bin/env python3
#
# ptxast.py
#
# Temporary AST (hopefully we can replace this with something generated by ASDL)
#
# Author: Sreepathi Pai
#

class PTXAST:
    pass

class IntLiteral(PTXAST):
    def __init__(self, value, unsigned):
        self.value = value
        self.unsigned = unsigned

    def __str__(self):
        return f"IntLiteral(value={self.value}, unsigned={self.unsigned})"

    __repr__ = __str__

class BinOp(PTXAST):
    def __init__(self, op, lhs, rhs):
        self.op = op
        self.lhs = lhs
        self.rhs = rhs

    def __str__(self):
        return f"BinOp(op={self.op}, lhs={self.lhs}, rhs={self.rhs})"

    __repr__ = __str__

class Unop(PTXAST):
    def __init__(self, op, expr):
        self.op = op
        self.expr = expr

    def __str__(self):
        return f"Unop(op={self.op}, expr={self.expr})"

    __repr__ = __str__


